#!/usr/bin/env python3
import sys


def main():
    coverage_path = sys.argv[1]

    with open(coverage_path, 'rb') as f:
        coverage = f.read()

    size = len(coverage)
    count = sum(map(lambda b: int(bool(b)), coverage))

    print('{} / {}'.format(count, size))
    print('{} %'.format(count / size * 100))


if __name__ == '__main__':
    main()