parameters:
- name: testTarget
  type: string

- name: jobName
  type: string

- name: pr
  type: string

- name: skip_update
  type: string


jobs:
  - job: ${{parameters.jobName}}
    variables:
      testTarget: ${{parameters.testTarget}}
    steps:
    - template: common-steps.yml
      parameters:
        pr: ${{ parameters.pr }}
        skip_update: ${{parameters.skip_update}}
    - pwsh: |
        python -m venv .env
        . ./.env/bin/Activate.ps1
        cd $(Build.SourcesDirectory)/checkpr
        pip install install -q wheel
        pip install -q -r requirements.txt
        pip install sdk/onefuzztypes-*.whl
        pip install sdk/onefuzz-*.whl
        cd integration

        Set-PSDebug -Trace 1
        $launch_result = python integration-test.py launch . --endpoint $(instance_endpoint) --client_id $(client_id) --client_secret $(client_secret) --targets $(testTarget) --test_id $(test_id) -v
        if ($LASTEXITCODE -ne 0) {
          throw "failed to launch"
        }

        if ($launch_result -join "" -notmatch "launch info:(.+)") {
          throw "invalid launch result: {$launch_result}"
        }
        $launch_info = $Matches[1] | ConvertFrom-Json
        job_ids = launch_info.jobs -join " "

        python integration-test.py check_results $(test_id) --endpoint $(instance_endpoint) --client_id $(client_id) --client_secret $(client_secret) --job_ids $job_ids -v
        if ($LASTEXITCODE -ne 0) {
          throw "result check failed"
        }

      displayName: 'test ${{ parameters.testTarget }}'