[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-C",
    "control-flow-guard",
    "-C",
    "link-arg=/DYNAMICBASE",
    "-C",
    "link-arg=/CETCOMPAT",
]
