[package]
name = "cobertura"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
quick-xml = { git = "https://github.com/tevoinea/quick-xml/", branch = "tevoinea/AsyncElementWriter", features = [
    "async-tokio",
] }
tokio = "1"
async-trait = "0.1"
