[licenses]
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "Zlib",
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
ignore = [
    "RUSTSEC-2022-0048", # xml-rs is unmaintained
    "RUSTSEC-2023-0018"
]

[bans]

# disallow rustls; we must use OpenSSL
[[bans.deny]]
name = "rustls"

# disallow ring; unapproved crypto
[[bans.deny]]
name = "ring"
